<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Hero', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","height":{"Desktop":{"unit":"px"}},"gap":"no","elementId":"guten-6TULi4"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-vxuGpS","background":{"type":"gradient","gradientColor":[{"color":"rgba(1, 18, 34, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(18, 27, 98, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":45},"verticalAlign":{"Desktop":"space-between"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"center"},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"80","bottom":"80","left":"80"}},"Mobile":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-BszoNm","content":"👋 Hi! We are Unibiz!","type":6,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0.05309734513274336}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"100","bottom":"100","left":"100"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-border"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"7","right":"16","bottom":"7","left":"16"}}},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/wrapper {"elementId":"guten-wRsOis","displayType":"flex","displayWidth":{"Tablet":{"unit":"px"}},"displayHeight":{"Tablet":{"unit":"px"}},"horizontalAlign":{"Desktop":false,"Tablet":"center","Mobile":false}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-OqOF44","content":"Built a Strong Online Presence Business","type":1,"textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"64"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.125"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"775"}}} /-->

<!-- wp:gutenverse/wrapper {"elementId":"guten-wypnuY"} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-Xl88Zs","gap":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"},"Tablet":{"unit":"px"}},"alignment":{"Tablet":"center","Desktop":"left"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"},"Mobile":{"unit":"px"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"unit":"px","point":"505"}}} -->
<!-- wp:paragraph -->
<p>Build any website you want for business, portfolio, blogging, or freelancer, faster and lighter using just one theme.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/wrapper -->

<!-- wp:gutenverse/button {"elementId":"guten-8rU2Xy","content":"Get Started Now","alignButton":{"Desktop":"center","Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"24","bottom":"17","left":"24"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"13","bottom":"15"}}},"buttonBackground":{"type":"gradient","gradientColor":[{"color":"rgba(159, 101, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(72, 57, 240, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"9","right":"9","bottom":"9","left":"9"}}}},"background":{"type":"gradient","color":{"type":"variable","id":"custom-text-primary"},"gradientColor":[{"color":"rgba(207, 178, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(73, 58, 241, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"600","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"}},"hoverTextColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"positioningType":{"Desktop":"inline"}} /-->
<!-- /wp:gutenverse/wrapper -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":"100"},"elementId":"guten-mPsb0o","background":{"type":"default","image":{"Desktop":{"id":3013,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/image-hero.webp","width":1920,"height":1281,"altOriginal":""}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(1, 18, 34, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(1, 18, 34, 0.2)","active":true,"opacity":0.2,"id":2,"offset":"0.976"}],"gradientType":"linear","gradientAngle":"0"},"opacity":"0.6"} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-OZZnBP","space":{"Desktop":{"unit":"px","point":"725"},"Tablet":{"unit":"px","point":"500"},"Mobile":{"unit":"px","point":"300"}}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
